// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsM3jr2miuJX_jJaH3S0KdL2mdg5D_uHA',
    appId: '1:454526047789:web:51456f32dbf7cd78180aa4',
    messagingSenderId: '454526047789',
    projectId: 'intellispend-9721',
    authDomain: 'intellispend-9721.firebaseapp.com',
    storageBucket: 'intellispend-9721.firebasestorage.app',
    measurementId: 'G-N5C0K3GDGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE8v1BSyxort1XzGIm96rKVw27SO3jgu4',
    appId: '1:454526047789:android:b140dff4ee86e15f180aa4',
    messagingSenderId: '454526047789',
    projectId: 'intellispend-9721',
    storageBucket: 'intellispend-9721.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAApj0Ewl_3XpIEFgKAx5JO3743XE7mncY',
    appId: '1:454526047789:ios:41979c22dc11c18d180aa4',
    messagingSenderId: '454526047789',
    projectId: 'intellispend-9721',
    storageBucket: 'intellispend-9721.firebasestorage.app',
    iosBundleId: 'com.example.intellispend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAApj0Ewl_3XpIEFgKAx5JO3743XE7mncY',
    appId: '1:454526047789:ios:41979c22dc11c18d180aa4',
    messagingSenderId: '454526047789',
    projectId: 'intellispend-9721',
    storageBucket: 'intellispend-9721.firebasestorage.app',
    iosBundleId: 'com.example.intellispend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsM3jr2miuJX_jJaH3S0KdL2mdg5D_uHA',
    appId: '1:454526047789:web:d7cc349ce7876e73180aa4',
    messagingSenderId: '454526047789',
    projectId: 'intellispend-9721',
    authDomain: 'intellispend-9721.firebaseapp.com',
    storageBucket: 'intellispend-9721.firebasestorage.app',
    measurementId: 'G-VK65LDTV7V',
  );
}
